FROM node:16-alpine AS deps

ENV NODE_ENV=production

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# 
FROM node:16-alpine AS builder

ENV NODE_ENV=production
WORKDIR /app

COPY next.config.js ./
COPY package.json yarn.lock ./
COPY --from=deps /app/node_modules ./node_modules

COPY . ./

RUN yarn build

# 
FROM node:16-alpine AS runner
CMD ["yarn", "dev"]