version: '3'

services:
  frontend:
    image: shalfey-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000 
    volumes:
      - ./frontend/src:/web/src
      - ./frontend/public:/web/public