version: '3'

services:
  frontend:
    image: shalfey-frontend
    build:
      context: frontend
      dockerfile: Dockerfile.production
    ports:
      - 3000:3000
    # volumes:
    #   - ./frontend/src:/web/src
    #   - ./frontend/public:/web/public
  nginx:
    image: nginx:latest
    # build:
    #   context: nginx
    #   dockerfile: Dockerfile
    # volumes: 
    environment:
      PUBLIC_SERVER_HOST: localhost
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    links:
      - frontend
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      -  ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - frontend
      - certbot
  certbot:
    image: certbot/certbot:latest
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
