# Generated by Django 3.2.19 on 2023-06-12 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.vendor'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='products.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='diseases',
            field=models.ManyToManyField(related_name='products', to='products.Disease'),
        ),
        migrations.AddField(
            model_name='product',
            name='herbsets',
            field=models.ManyToManyField(related_name='products', to='products.HerbSet'),
        ),
        migrations.AddField(
            model_name='medicinebranch',
            name='categories',
            field=models.ManyToManyField(related_name='branch', to='products.Category'),
        ),
        migrations.AddField(
            model_name='medicinebranch',
            name='herbsets',
            field=models.ManyToManyField(related_name='branch', to='products.HerbSet'),
        ),
        migrations.AddField(
            model_name='medicinebranch',
            name='products',
            field=models.ManyToManyField(related_name='branch', to='products.Product'),
        ),
        migrations.AddField(
            model_name='herbset',
            name='subsets',
            field=models.ManyToManyField(blank=True, related_name='supersets', to='products.HerbSet'),
        ),
        migrations.AddField(
            model_name='disease',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='supercategories', to='products.Disease'),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='supercategories', to='products.Category'),
        ),
    ]
