# Generated by Django 3.2.19 on 2023-06-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230621_1608'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shopuser',
            managers=[
            ],
        ),
    ]
