# Generated by Django 3.2.19 on 2023-06-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_vendor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='basket',
        ),
    ]
